### ISSUE TITLE
Feature request - a setting for the number of files uploaded per hour

### ISSUE THREAD

**Issue by tissole** [Nekmo/telegram-upload#132] opened 2021-09-17 17:05 UTC
In the case of very small files, users may hit the TG limit, which is about 2000 files uploaded per hour.  Then, the flood errors occur and the script stops for a period. After that, it can restart automatically or the user must manually restart it?

Can you make an option so that the script restart automatically if that is the case? Also, please add an option for users to choose the number of files uploaded per hour. It will be very useful for uploading small files and preventing flood warnings to occur.

**Comment by Nekmo** [comment] 2021-09-17 21:04
This issue is a duplicate of #111. Put your comments in the other task, thanks.

**Closed by Nekmo** 2021-09-17 21:04 UTC

**Comment by tissole** [comment] 2021-09-18 07:46
Yes, it resembles in one aspect, flood errors, but the causes and solutions are different. In that case, the error is caused by using the chat invite link for the destination channel, in my case, the cause is uploading too many files per hour. In that case, the solution is to use chat ID, in my case, the solution is to limit the number of files uploaded per hour to respect the Telegram limit, which is about 2000 files per hour.

**Comment by Wajalot** [comment] 2023-01-15 12:00
It would be perfect. To limit the files to upload per hour. Also, take the time since script starts and upload 2000 files, if the time is less than hour make a pause for the difference time and restart after it.
